name: Build and deploy ASP.Net Core app to Azure Web App - CommPinboardDB

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore /api/CommPinboardDB/CommPinboardDB.sln  # ✅ Pointing to solution file

      - name: Build with dotnet
        run: dotnet build /api/CommPinboardDB.sln --configuration Release --no-restore  # ✅ Specify solution

      - name: dotnet publish
        run: dotnet publish /api/CommPinboardDB/CommPinboardDB.csproj -c Release -o "${{github.workspace}}/published-app"  # ✅ Pointing to project

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{github.workspace}}/published-app  # ✅ Use correct path

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # Required for JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./published-app  # ✅ Set correct path for deployment
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_916D096529A14121A722B26D9D21C373 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C33E5E8492A3419CBD60887646321FA4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D596518870D54497BA8934EF1F0166E5 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CommPinboardDB'
          slot-name: 'Production'
          package: ./published-app  # ✅ Correct deployment path
